<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Audit_tray extends MY_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model(['Settings_model', 'Audit_model', 'Department_model', 'Anouncement_model', 'Login_model', 'Audit_model']);
        $this->load->library('form_validation');
         $this->login = $this->session->userdata('cms_logged_in'); 
         $this->department_id=$this->login['department_id'];
        $this->admin_id=$this->login['admin_id'];
         $this->user_id=$this->login['user_id'];
        $this->emails=$this->login['email'];
    }

    public function index()
    {
        $req_list= $this->Audit_model->get_all(); 
         $department_status= $this->Department_model->get_by_id($this->department_id);
        $data = array(
          'title' => 'Audit',
            'req_list'=>$req_list,
            'department_status'=> $department_status,
        );
        $this->template->load('template', 'audit/list', $data);
    } 
    
   
}

/* End of file Master_plan.php */
/* Location: ./application/controllers/Master_plan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-16 14:17:34 */
/* http://harviacode.com */